
[tool.poetry]
name = "pympistandard"
version = "0.1.0"
description = "Python API to the MPI Standard"
authors = ["Martin Ruefenacht <martin.ruefenacht@lrz.de>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^7.0.1"
pytest-sugar = "^0.9.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
